use Planificacion_Academica;
select * from cargo;
insert into cargo (DESCRIPCION) VALUES ("DIRECTOR");
insert into cargo (DESCRIPCION) VALUES ("SUB-DIRECTOR");
insert into cargo (DESCRIPCION) VALUES ("SECRETARIA");
insert into cargo (DESCRIPCION) VALUES ("INSPECTOR");

select * from modalidad;
insert into modalidad (DESCRIPCION) VALUES ("PRE-ESCOLAR FORMAL");
insert into modalidad (DESCRIPCION) VALUES ("PRIMARIA REGULAR");
insert into modalidad (DESCRIPCION) VALUES ("SECUNDARIA DIURNA");
insert into modalidad (DESCRIPCION) VALUES ("SECUNDARIA A DISTANCIA JYA");

select * from anio_electivo;
insert into anio_electivo (DESCRIPCION) VALUES ("2020");
insert into anio_electivo (DESCRIPCION) VALUES ("2021");
insert into anio_electivo (DESCRIPCION) VALUES ("2022");

select * from dia;
insert into dia (DESCRIPCION) VALUES ("LUNES");
insert into dia (DESCRIPCION) VALUES ("MARTES");
insert into dia (DESCRIPCION) VALUES ("MIERCOLES");
insert into dia (DESCRIPCION) VALUES ("JUEVES");
insert into dia (DESCRIPCION) VALUES ("VIERNES");
insert into dia (DESCRIPCION) VALUES ("SABADO");


select * from dia;
update dia set DESCRIPCION = "LUNES" WHERE ID=1;
update dia set DESCRIPCION = "MARTES" WHERE ID=2;
update dia set DESCRIPCION = "MIERCOLES" WHERE ID=3;
update dia set DESCRIPCION = "JUEVES" WHERE ID=4;
update dia set DESCRIPCION = "VIERNES" WHERE ID=5;



select * from grado;
insert into grado (DESCRIPCION) VALUES ("I NIVEL");
insert into grado (DESCRIPCION) VALUES ("II NIVEL");
insert into grado (DESCRIPCION) VALUES ("III NIVEL");
insert into grado (DESCRIPCION) VALUES ("PRIMERO");
insert into grado (DESCRIPCION) VALUES ("SEGUNDO");
insert into grado (DESCRIPCION) VALUES ("TERCERO");
insert into grado (DESCRIPCION) VALUES ("CUARTO");
insert into grado (DESCRIPCION) VALUES ("QUINTO");
insert into grado (DESCRIPCION) VALUES ("SEPTIMO");
insert into grado (DESCRIPCION) VALUES ("OCTAVO");
insert into grado (DESCRIPCION) VALUES ("NOVENO");
insert into grado (DESCRIPCION) VALUES ("DECIMO");
insert into grado (DESCRIPCION) VALUES ("UNDECIMO");

select * from modalidad;
insert into modalidad(DESCRIPCION) VALUES ('PREESCOLAR COMUNITARIO');

/*INSERTANDO LAS SECCIONES*/
INSERT INTO SECCION (DESCRIPCION) VALUES ('A');
INSERT INTO SECCION (DESCRIPCION) VALUES ('B');
INSERT INTO SECCION (DESCRIPCION) VALUES ('C');


/*INSERTANDO TURNO*/
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('MATURINO','8:00 AM - 11:00 AM');
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('MATURINO','7:00 AM - 12:00 MD');
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('VESPERTINO','12:30 AM - 5:15 PM');
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('SABATINO','8:00 AM - 4:00 PM');

select * from turno;
update turno set DESCRIPCION = 'MATUTINO' WHERE ID = 2 AND ID=2;

/*INSERTANDO TRES MAESTRAS DE PREESCOLAR-*/
SELECT * FROM DOCENTE;
INSERT INTO DOCENTE VALUES ('448-150492-0012Q','KARLA','ELIZABETH','JARQUIN','CALERO','1992-04-15','85974196','DIRECCION','karli123','123','F',40,1);
INSERT INTO DOCENTE VALUES ('001-190890-0001A','MEYLING','ESTEFANIA','PEREZ','VELASQUEZ','1990-08-19','54897450','DIRECCION','mey123','123','F',40,1);
INSERT INTO DOCENTE VALUES ('001-200991-0012P','AURORA','ABIGAIL','ZAMORA','JARQUIN','1991-09-20','85967410','DIRECCION','auro123','123','F',40,1);




SELECT * FROM GRUPO_GRADO;
SELECT * FROM GRADO;
SELECT * FROM SECCION;
SELECT * FROM TURNO;
SELECT * FROM MODALIDAD;
SELECT * FROM DOCENTE;
INSERT INTO GRUPO_GRADO (ID_GRADO,ID_SECCION,ID_TURNO,ID_MODALIDAD,CEDULA_DOCENTE) VALUES (1,1,1,9,'448-150492-0012Q');
INSERT INTO GRUPO_GRADO (ID_GRADO,ID_SECCION,ID_TURNO,ID_MODALIDAD,CEDULA_DOCENTE) VALUES (2,1,1,9,'001-190890-0001A');
INSERT INTO GRUPO_GRADO (ID_GRADO,ID_SECCION,ID_TURNO,ID_MODALIDAD,CEDULA_DOCENTE) VALUES (3,1,1,9,'001-200991-0012P');

/*CONSULTA PARA CONOCER LOS DOCENTES Y GRADOS QUE GUIAN*/
SELECT D.CEDULA,D.PRIMER_NOMBRE,D.PRIMER_APELLIDO, M.DESCRIPCION, G.DESCRIPCION, S.DESCRIPCION, T.DESCRIPCION FROM DOCENTE D inner join GRUPO_GRADO GG ON D.CEDULA = GG.CEDULA_DOCENTE
						inner join MODALIDAD M ON GG.ID_MODALIDAD = M.ID
                        INNER JOIN GRADO G ON GG.ID_GRADO = G.ID
                        INNER JOIN TURNO T ON GG.ID_TURNO = T.ID
                        INNER JOIN SECCION S ON GG.ID_SECCION = S.ID;
                        
/*INSERTANDO ESTUDIANTES DE PRIMER NIVEL DE PREESCOLAR*/
SELECT * FROM ESTUDIANTE where ID_GRUPO_GRADO = 2;

/*COMENTARIO*/







select * FROM GRUPO_GRADO;
SELECT * FROM GRADO;


/*INSERTANDO TRES MAESTRAS DE PREESCOLAR-*/
SELECT * FROM personal;
INSERT INTO DOCENTE VALUES ('448-150492-0012Q','KARLA','ELIZABETH','JARQUIN','CALERO','1992-04-15','85974196','DIRECCION','karli123','123','F',40,1);





/*DE AQUI HACIA ABAJO ESTA EL CODIGO QUE SE IMPLEMENTO LUEGO DE LA RETROALIMENTACION*/
          /**/
          /**/
          /**/
          /**/
/**/     /**/          /**/
  /**/             /**/       
      /**/    /**/
		  /**/






/*REALIZANDO VERIFICACION E INCERSION DE DATOS EN LA BD*/

select * from actividad;


/*INSERTANDO CARGO Y SU DESCRIPCION*/
SELECT * FROM CARGO;
INSERT INTO CARGO (DESCRIPCION) VALUES ("DOCENTE");
INSERT INTO CARGO (DESCRIPCION) VALUES ("DIRECTOR");
INSERT INTO CARGO (DESCRIPCION) VALUES ("SUB DIRECTOR");
INSERT INTO CARGO (DESCRIPCION) VALUES ("INSPECTOR");


/*INSERTANDO DATOS DE PERSONAL*/
/*DOCENTES*/
select * from personal;
INSERT INTO PERSONAL VALUES ("001-070997-0031X","MEYLING","ESTEFANIA","PEREZ","VELASQUEZ","1997-07-09","77774033","PARQUE MATEARE 2 CUADRAS AL SUR",40,"mey123","mey123",1,1);
INSERT INTO PERSONAL VALUES ("001-100494-0001V","MARIA","MAGDALENA","URROZ","BLANDON","1994-04-10","88897312","CIUDAD SANDINO TOPE SUR",40,"mari123","mari123",1,1);
INSERT INTO PERSONAL VALUES ("001-180990-0004Z","SOFIA","SARAI","MARTINEZ","RUIZ","1990-09-18","89903242","PARQUE MATEARE 7 CUADRAS LA NORTE",40,"sofiy123","sofi123",1,1);
INSERT INTO PERSONAL VALUES ("001-230890-0031X","DINA","SARA","CASTRO","FLORES","1990-08-23","77774033","CARRETERA VIEJA A LEON KM 29",10,"dina123","dina123",1,1);
INSERT INTO PERSONAL VALUES ("001-070991-0011Q","ANDREA","ANTONIA","SILVA","GUIDO","1991-07-09","77774033","PARQUE MATEARE 7 CUADRAS AL SUR",0,"andy123","andy123",1,1);
INSERT INTO PERSONAL VALUES ("001-070989-0041P","MARJORIE","JACQUELINE","MEMBREÑO","CASTRO","1989-07-09","88124033","ENTRADA PRINCIPAL CIUDAD SANDINO 2 CUADRAS AL SUR",0,"marjo123","marjo123",1,1);
INSERT INTO PERSONAL VALUES ("001-070989-0239L","MARIA","ELIZABETH","ARAGON","ROA","1989-07-09","78974033","PARQUE MATEARE 3 CUADRAS AL SUR",0,"mari123","mari123",1,1);
INSERT INTO PERSONAL VALUES ("001-070999-0231S","ESTELA","RACHEL","PEREZ","BRIONES","1999-07-09","79974033","PARQUE MATEARE 2 CUADRAS AL SUR",0,"este123","este123",1,1);
INSERT INTO PERSONAL VALUES ("001-070999-0043W","SEBASTIAN","JOSE","MEZA","PEREZ","1999-07-09","77774033","PARQUE MATEARE 2 CUADRAS AL SUR",0,"sebas123","sebas123",1,1);
INSERT INTO PERSONAL VALUES ("001-070992-0031X","MARCO","AURELIO","ALEMAN","SOLIS","1992-07-09","77774033","PARQUE MATEARE 2 CUADRAS AL SUR",0,"marco123","marco123",1,1);
INSERT INTO PERSONAL VALUES ("001-070984-0031F","MAGDA","VERONICA","FLORES","LOPEZ","1984-07-09","F","77774033","CIUDAD SANDINO ENTRANDA PRINCIPAL 2 CUADRAS AL SUR",0,"magda123","magdaco123",1,2);
INSERT INTO PERSONAL VALUES ("001-070990-0031F","YURI","PATRICIA","HERNANDEZ","RAMIREZ","1990-07-09","F","77774033","CIUDAD SANDINO ENTRANDA PRINCIPAL 7 CUADRAS AL SUR",0,"yuri123","yuri123",1,3);



/*INSERTANDO LAS MODALIDADES*/
select * from modalidad;
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("PREESCOLAR COMUNITARIO");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("PREESCOLAR FORMAL");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("PREESCOLAR MULTINIVEL");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("PRIMARIA REGULAR");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("PRRIMARIA EXTRAEDAD");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("SECUNDARIA DIURNA");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("SECUNDARIA NOCTURNA");
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ("SECUNDARIA POR ENCUENTRO");


/*INSERTANDO SECCIONES*/
SELECT * FROM SECCION;
INSERT INTO SECCION (DESCRIPCION) VALUES ("SECCION A");
INSERT INTO SECCION (DESCRIPCION) VALUES ("SECCION B");
INSERT INTO SECCION (DESCRIPCION) VALUES ("SECCION C");

/*INSERTANTO TURNO*/
SELECT * FROM TURNO;
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ("MATUTINO","7:00 AM - 12:00 MD");
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ("MATUTINO","8:00 AM - 11:00 AM");
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ("VESPERTINO","12:30 MD - 5:15 PM");
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ("SABATINO","8:00 AM - 4:00 PM");

/*INSERTANDO DIA*/
SELECT * FROM DIA;
INSERT INTO DIA (DESCRIPCION) VALUES ("LUNES");
INSERT INTO DIA (DESCRIPCION) VALUES ("MARTES");
INSERT INTO DIA (DESCRIPCION) VALUES ("MIERCOLES");
INSERT INTO DIA (DESCRIPCION) VALUES ("JUEVES");
INSERT INTO DIA (DESCRIPCION) VALUES ("VIERENES");
INSERT INTO DIA (DESCRIPCION) VALUES ("SABADO");

/*INSERTANDO ASIGNATURA*/
SELECT * FROM ASIGNATURA;
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("LENGUA Y LITERATURA");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("MATEMATICAS");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("APRENDER A EMPRENDER Y PROSPERAR");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("CIENCIAS SOCIALES");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("CIENCIAS NATURALES");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("EDUCACION FISICA");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("DERECHOS Y DIGNIDAD DE LA MUJER");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("FISICA");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("QUIMICA");
INSERT INTO ASIGNATURA (DESCRIPCION) VALUES ("BIOLOGIA");

/*INSERTANDO LOS HORARIOS DE CADA BLOQUE*/
SELECT * FROM HORARIO_BLOQUE;
SELECT * FROM HORARIO_DESIGNADO;



SELECT * FROM HORARIO_DESIGNADO;
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 1","7:00 AM - 7:45 AM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 2","7:45 AM - 8:30 AM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 3","8:30 AM - 9:15 AM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 4","9:15 AM - 10:00 AM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("RECESO","10:00 AM - 10:30 AM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 5","10:30 AM - 11:15 AM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 6","11:15 AM - 12:00 MD");

INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 1","12:30 MD - 1:15 PM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 2","1:15 PM - 2:00 PM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 3","2:00 PM - 2:45 PM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 4","2:45 PM - 3:30 PM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("RECESO","3:30 PM - 3:45 PM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 5","3:45 PM - 4:30 PM");
INSERT INTO horario_designado (DESCRIPCION,HORARIO) VALUES ("BLOQUE 6","4:30 PM - 5:15 PM");

select * from grado;
INSERT INTO GRADO(DESCRIPCION) VALUES ("I NIVEL");
INSERT INTO GRADO(DESCRIPCION) VALUES ("II NIVEL");
INSERT INTO GRADO(DESCRIPCION) VALUES ("III NIVEL");
INSERT INTO GRADO(DESCRIPCION) VALUES ("PRIMER GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("SEGUNDO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("TERCER GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("CUARTO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("QUINTO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("SEXTO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("SEPTIMO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("OCTAVO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("NOVENO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("DECIMO GRADO");
INSERT INTO GRADO(DESCRIPCION) VALUES ("UNDECIMO GRADO");


SELECT * FROM PERSONAL WHERE ID_CARGO =1;
SELECT * FROM GRADO;
SELECT * FROM SECCION;
SELECT * FROM TURNO;
SELECT * FROM MODALIDAD;
SELECT * FROM GRUPO;

