use Planificacion_Academica;
select * from cargo;
insert into cargo (DESCRIPCION) VALUES ("DIRECTOR");
insert into cargo (DESCRIPCION) VALUES ("SUB-DIRECTOR");
insert into cargo (DESCRIPCION) VALUES ("SECRETARIA");
insert into cargo (DESCRIPCION) VALUES ("INSPECTOR");

select * from modalidad;
insert into modalidad (DESCRIPCION) VALUES ("PRE-ESCOLAR FORMAL");
insert into modalidad (DESCRIPCION) VALUES ("PRIMARIA REGULAR");
insert into modalidad (DESCRIPCION) VALUES ("SECUNDARIA DIURNA");
insert into modalidad (DESCRIPCION) VALUES ("SECUNDARIA A DISTANCIA JYA");

select * from anio_electivo;
insert into anio_electivo (DESCRIPCION) VALUES ("2020");
insert into anio_electivo (DESCRIPCION) VALUES ("2021");
insert into anio_electivo (DESCRIPCION) VALUES ("2022");

select * from dia;
insert into dia (DESCRIPCION) VALUES ("LUNES");
insert into dia (DESCRIPCION) VALUES ("MARTES");
insert into dia (DESCRIPCION) VALUES ("MIERCOLES");
insert into dia (DESCRIPCION) VALUES ("JUEVES");
insert into dia (DESCRIPCION) VALUES ("VIERNES");
insert into dia (DESCRIPCION) VALUES ("SABADO");


select * from dia;
update dia set DESCRIPCION = "LUNES" WHERE ID=1;
update dia set DESCRIPCION = "MARTES" WHERE ID=2;
update dia set DESCRIPCION = "MIERCOLES" WHERE ID=3;
update dia set DESCRIPCION = "JUEVES" WHERE ID=4;
update dia set DESCRIPCION = "VIERNES" WHERE ID=5;



select * from grado;
insert into grado (DESCRIPCION) VALUES ("I NIVEL");
insert into grado (DESCRIPCION) VALUES ("II NIVEL");
insert into grado (DESCRIPCION) VALUES ("III NIVEL");
insert into grado (DESCRIPCION) VALUES ("PRIMERO");
insert into grado (DESCRIPCION) VALUES ("SEGUNDO");
insert into grado (DESCRIPCION) VALUES ("TERCERO");
insert into grado (DESCRIPCION) VALUES ("CUARTO");
insert into grado (DESCRIPCION) VALUES ("QUINTO");
insert into grado (DESCRIPCION) VALUES ("SEPTIMO");
insert into grado (DESCRIPCION) VALUES ("OCTAVO");
insert into grado (DESCRIPCION) VALUES ("NOVENO");
insert into grado (DESCRIPCION) VALUES ("DECIMO");
insert into grado (DESCRIPCION) VALUES ("UNDECIMO");

select * from modalidad;
insert into modalidad(DESCRIPCION) VALUES ('PREESCOLAR COMUNITARIO');

/*INSERTANDO LAS SECCIONES*/
INSERT INTO SECCION (DESCRIPCION) VALUES ('A');
INSERT INTO SECCION (DESCRIPCION) VALUES ('B');
INSERT INTO SECCION (DESCRIPCION) VALUES ('C');


/*INSERTANDO TURNO*/
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('MATURINO','8:00 AM - 11:00 AM');
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('MATURINO','7:00 AM - 12:00 MD');
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('VESPERTINO','12:30 AM - 5:15 PM');
INSERT INTO TURNO (DESCRIPCION,HORARIO) VALUES ('SABATINO','8:00 AM - 4:00 PM');

select * from turno;
update turno set DESCRIPCION = 'MATUTINO' WHERE ID = 2 AND ID=2;

/*INSERTANDO TRES MAESTRAS DE PREESCOLAR-*/
SELECT * FROM DOCENTE;
INSERT INTO DOCENTE VALUES ('448-150492-0012Q','KARLA','ELIZABETH','JARQUIN','CALERO','1992-04-15','85974196','DIRECCION','karli123','123','F',40,1);
INSERT INTO DOCENTE VALUES ('001-190890-0001A','MEYLING','ESTEFANIA','PEREZ','VELASQUEZ','1990-08-19','54897450','DIRECCION','mey123','123','F',40,1);
INSERT INTO DOCENTE VALUES ('001-200991-0012P','AURORA','ABIGAIL','ZAMORA','JARQUIN','1991-09-20','85967410','DIRECCION','auro123','123','F',40,1);




SELECT * FROM GRUPO_GRADO;
SELECT * FROM GRADO;
SELECT * FROM SECCION;
SELECT * FROM TURNO;
SELECT * FROM MODALIDAD;
SELECT * FROM DOCENTE;
INSERT INTO GRUPO_GRADO (ID_GRADO,ID_SECCION,ID_TURNO,ID_MODALIDAD,CEDULA_DOCENTE) VALUES (1,1,1,9,'448-150492-0012Q');
INSERT INTO GRUPO_GRADO (ID_GRADO,ID_SECCION,ID_TURNO,ID_MODALIDAD,CEDULA_DOCENTE) VALUES (2,1,1,9,'001-190890-0001A');
INSERT INTO GRUPO_GRADO (ID_GRADO,ID_SECCION,ID_TURNO,ID_MODALIDAD,CEDULA_DOCENTE) VALUES (3,1,1,9,'001-200991-0012P');

/*CONSULTA PARA CONOCER LOS DOCENTES Y GRADOS QUE GUIAN*/
SELECT D.CEDULA,D.PRIMER_NOMBRE,D.PRIMER_APELLIDO, M.DESCRIPCION, G.DESCRIPCION, S.DESCRIPCION, T.DESCRIPCION FROM DOCENTE D inner join GRUPO_GRADO GG ON D.CEDULA = GG.CEDULA_DOCENTE
						inner join MODALIDAD M ON GG.ID_MODALIDAD = M.ID
                        INNER JOIN GRADO G ON GG.ID_GRADO = G.ID
                        INNER JOIN TURNO T ON GG.ID_TURNO = T.ID
                        INNER JOIN SECCION S ON GG.ID_SECCION = S.ID;
                        
/*INSERTANDO ESTUDIANTES DE PRIMER NIVEL DE PREESCOLAR*/
SELECT * FROM ESTUDIANTE where ID_GRUPO_GRADO = 2;

/*COMENTARIO*/




select * FROM GRUPO_GRADO;
SELECT * FROM GRADO;