create database Planificacion_Academica;
use Planificacion_Academica;

/*CREACION DE TABLAS*/

CREATE TABLE MODALIDAD
(
	ID INT PRIMARY KEY auto_increment,
    DESCRIPCION VARCHAR(35)
);

CREATE TABLE TURNO
(
	ID INT PRIMARY KEY auto_increment,
    DESCRIPCION VARCHAR(35) NOT NULL,
    HORARIO VARCHAR(35) NOT NULL
);

CREATE TABLE SECCION
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE DIA
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE CARGO
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE PERSONAL
(
	CEDULA CHAR(18) PRIMARY KEY NOT NULL,
    PRIMER_NOMBRE VARCHAR(35) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(35),
    PRIMER_APELLIDO VARCHAR(35) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(35),
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR(8),
    DIRECCION VARCHAR(100),
    USSER VARCHAR(20) NOT NULL,
    CONTRA VARCHAR(20) NOT NULL,
    ESTADO BIT NOT NULL,
    ID_CARGO INT NOT NULL,
    CONSTRAINT FK_CARGO_PADMIN FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ACTIVIDAD
(
	ID INT PRIMARY KEY auto_increment,
	NOMBRE VARCHAR(35) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    LUGAR VARCHAR(40),
    CEDULA_PERSONAL CHAR(18),
    CONSTRAINT FK_PERSONAL_ACTIVIDAD FOREIGN KEY (CEDULA_PERSONAL) REFERENCES PERSONAL (CEDULA) 
);

CREATE TABLE GRUPO
(
	ID INT PRIMARY KEY auto_increment NOT NULL,
    ID_GRADO INT,
    ID_SECCION INT NOT NULL,
    ID_TURNO INT NOT NULL,
    ID_MODALIDAD INT NOT NULL,
    CEDULA_PERSONAL CHAR(18),
    CONSTRAINT FK_GRADO_SECCION FOREIGN KEY (ID_SECCION) REFERENCES SECCION (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GRADO_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNO (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GRADO_MODALIDAD FOREIGN KEY(ID_MODALIDAD) REFERENCES MODALIDAD (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GRADO_PERSONAL FOREIGN KEY (CEDULA_PERSONAL) REFERENCES PERSONAL (CEDULA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ASIGNATURA
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE DOCENTE_ASIGNATURA
(
	ID INT PRIMARY KEY auto_increment,
    ID_ASIGNATURA INT NOT NULL,
    CEDULA_PERSONAL CHAR(18) NOT NULL,
    CONSTRAINT FK_DA_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DA_PERSONAL FOREIGN KEY (CEDULA_PERSONAL) REFERENCES PERSONAL (CEDULA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HORARIO_BLOQUE
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL,
    HORARIO VARCHAR(35) NOT NULL,
    ID_TURNO INT NOT NULL,
    CONSTRAINT FK_HB_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BLOQUE_CLASE
(
	ID INT PRIMARY KEY auto_increment,
	ID_DIA INT NOT NULL,
    ID_HORARIO_BLOQUE INT NOT NULL,
    ID_ASIGNATURA INT NOT NULL,
    ID_GRADO INT NOT NULL,
    CONSTRAINT FK_BC_DIA FOREIGN KEY (ID_DIA) REFERENCES DIA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BC_HB FOREIGN KEY (ID_HORARIO_BLOQUE) REFERENCES HORARIO_BLOQUE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BC_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BC_GRADO FOREIGN KEY (ID_GRADO) REFERENCES GRADO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);



create table anio_electivo
(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DESCRIPCION CHAR(4)
);


create table grado
(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR(40)
);
 
 
CREATE table HORARIO_DESIGNADO
(
	ID INT PRIMARY KEY auto_increment NOT NULL,
    DESCRIPCION VARCHAR(40)
);

create table Valoracion_Cualitativa(
ID INT primary key auto_increment  not null,
PREGUNTA_01 VARCHAR(350) NOT NULL,
PREGUNTA_02 VARCHAR(350) NOT NULL,
PREGUNTA_03 VARCHAR(350) NOT NULL,
PREGUNTA_04 VARCHAR(350) NOT NULL,
PREGUNTA_05 VARCHAR(350) NOT NULL
);


CREATE TABLE PLAN_DE_MEDIDAS
(
	ID INT primary key auto_increment  not null,
    PREGUNTA_01 VARCHAR(350) NOT NULL,
	PREGUNTA_02 VARCHAR(350) NOT NULL,
	PREGUNTA_03 VARCHAR(350) NOT NULL,
	PREGUNTA_04 VARCHAR(350) NOT NULL,
    PREGUNTA_05 VARCHAR(350) NOT NULL
);

CREATE TABLE ASIGNATURA_MODALIDAD
(
		ID INT primary key auto_increment  not null,
        ID_ASIGNATURA INT,
        ID_MODALIDAD INT,
        CONSTRAINT FK_ASIGNATURA_AM FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID),
        CONSTRAINT FK_MODALIDAD_AM FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDAD (ID)
        
);


CREATE TABLE MODALIDAD_GRADO
(
		ID INT primary key auto_increment  not null,
        ID_GRADO INT,
        ID_MODALIDAD INT,
        CONSTRAINT FK_GRADO_MG FOREIGN KEY (ID_GRADO) REFERENCES GRADO (ID),
        CONSTRAINT FK_MODALIDAD_MG FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDAD (ID)
);



CREATE TABLE MODALIDAD_BLOQUE
(
		ID INT primary key auto_increment  not null,
        ID_BLOQUE INT,
        ID_MODALIDAD INT,
        CONSTRAINT FK_BLOQUE_MB FOREIGN KEY (ID_BLOQUE) REFERENCES BLOQUE (ID),
        CONSTRAINT FK_MODALIDAD_MB FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDAD (ID)
);



 select * from actividad;
 select * from plan_de_medidas;
 select * from valoracion_cualitativa;
 
 
 alter table actividad ADD CONSTRAINT FK_ACTIVDAD_P_MEDIDA FOREIGN KEY (ID_P_MEDIDA) REFERENCES plan_de_medidas (ID);
alter table actividad ADD CONSTRAINT FK_ACTIVDAD_VALORACION_CUALITATIVA FOREIGN KEY (ID_V_CUALITATIVA) REFERENCES valoracion_cualitativa (ID);
 
 alter table bloque add constraint FK_BLOQUE_MODALIDAD FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDAD (ID);
alter table asignatura add constraint FK_ASIGNATURA_MODALIDAD FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDAD (ID);
 select * from bloque;
 select * from asignatura;
 
 select * from grupo;
 select * from grado;
 
 
 alter table bloque add constraint FK_BLOQUE_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNO (ID);
 
 