create database Planificacion_Academica;
use Planificacion_Academica;

/*CREACION DE TABLAS*/

CREATE TABLE MODALIDAD
(
	ID INT PRIMARY KEY auto_increment,
    DESCRIPCION VARCHAR(35)
);

CREATE TABLE TURNO
(
	ID INT PRIMARY KEY auto_increment,
    DESCRIPCION VARCHAR(35) NOT NULL,
    HORARIO VARCHAR(35) NOT NULL
);

CREATE TABLE SECCION
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE DIA
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE CARGO
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE ACTIVIDAD
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL,
    OBJETIVO VARCHAR(35) NOT NULL
);

CREATE TABLE EJECUCION
(
	ID INT PRIMARY KEY auto_increment,
	FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    ID_ACTIVIDAD INT NOT NULL,
    CONSTRAINT FK_EJECUCION_ACTIVIDAD FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDAD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE P_ADMIN
(
	CEDULA CHAR(18) PRIMARY KEY NOT NULL,
    PRIMER_NOMBRE VARCHAR(35) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(35),
    PRIMER_APELLIDO VARCHAR(35) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(35),
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR(8),
    DIRECCION VARCHAR(100),
    USSER VARCHAR(20) NOT NULL,
    CONTRA VARCHAR(20) NOT NULL,
    ESTADO BIT NOT NULL,
    ID_CARGO INT NOT NULL,
    CONSTRAINT FK_CARGO_PADMIN FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DOCENTE
(
	CEDULA CHAR(18) PRIMARY KEY NOT NULL,
    PRIMER_NOMBRE VARCHAR(35) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(35),
    PRIMER_APELLIDO VARCHAR(35) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(35),
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR(8),
    DIRECCION VARCHAR(100),
    USSER VARCHAR(20) NOT NULL,
    CONTRA VARCHAR(20) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    HORAS_LABORALES INT NOT NULL,
    ESTADO BIT NOT NULL
);

CREATE TABLE GRADO
(
	ID INT PRIMARY KEY auto_increment NOT NULL,
    DESCRIPCION VARCHAR(35),
    ID_SECCION INT NOT NULL,
    ID_TURNO INT NOT NULL,
    ID_MODALIDAD INT NOT NULL,
    CEDULA_DOCENTE CHAR(18),
    CONSTRAINT FK_GRADO_SECCION FOREIGN KEY (ID_SECCION) REFERENCES SECCION (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GRADO_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNO (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GRADO_MODALIDAD FOREIGN KEY(ID_MODALIDAD) REFERENCES MODALIDAD (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GRADO_DOCENTE FOREIGN KEY (CEDULA_DOCENTE) REFERENCES DOCENTE (CEDULA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ASIGNATURA
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL
);

CREATE TABLE DOCENTE_ASIGNATURA
(
	ID INT PRIMARY KEY auto_increment,
    ID_ASIGNATURA INT NOT NULL,
    CEDULA_DOCENTE CHAR(18) NOT NULL,
    CONSTRAINT FK_DA_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DA_DOCENTE FOREIGN KEY (CEDULA_DOCENTE) REFERENCES DOCENTE (CEDULA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HORARIO_BLOQUE
(
	ID INT PRIMARY KEY auto_increment,
	DESCRIPCION VARCHAR(35) NOT NULL,
    HORARIO VARCHAR(35) NOT NULL,
    ID_TURNO INT NOT NULL,
    CONSTRAINT FK_HB_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BLOQUE_CLASE
(
	ID INT PRIMARY KEY auto_increment,
	ID_DIA INT NOT NULL,
    ID_HORARIO_BLOQUE INT NOT NULL,
    ID_ASIGNATURA INT NOT NULL,
    ID_GRADO INT NOT NULL,
    CONSTRAINT FK_BC_DIA FOREIGN KEY (ID_DIA) REFERENCES DIA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BC_HB FOREIGN KEY (ID_HORARIO_BLOQUE) REFERENCES HORARIO_BLOQUE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BC_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BC_GRADO FOREIGN KEY (ID_GRADO) REFERENCES GRADO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ESTUDIANTE
(
	CODIGO VARCHAR(18) PRIMARY KEY NOT NULL,
    PRIMER_NOMBRE VARCHAR(35) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(35),
    PRIMER_APELLIDO VARCHAR(35) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(35),
    FECHA_NACIMIENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    ID_GRADO INT NOT NULL,
    CONSTRAINT FK_ESTUDIANTE_GRADO FOREIGN KEY (ID_GRADO) REFERENCES GRADO (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DETALLE_EJECUCION
(
	ID INT PRIMARY KEY auto_increment NOT NULL,
    CODIGO_ESTUDIANTE VARCHAR(18),
    CEDULA_DOCENTE CHAR(18),
    CEDULA_PADMIN CHAR(18),
    ID_EJECUCION INT NOT NULL,
    CONSTRAINT FK_DE_ESTUDIANTE FOREIGN KEY (CODIGO_ESTUDIANTE) REFERENCES ESTUDIANTE (CODIGO)ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_DE_DOCENTE FOREIGN KEY (CEDULA_DOCENTE) REFERENCES DOCENTE (CEDULA) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_DE_PADMIN FOREIGN KEY (CEDULA_PADMIN) REFERENCES P_ADMIN(CEDULA) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_DE_EJECUCION FOREIGN KEY (ID_EJECUCION) REFERENCES EJECUCION (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

create table anio_electivo
(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DESCRIPCION CHAR(4)
);


create table grado
(
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR(40)
);
 
 
 
 
 
 
 
 